from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/contracts/source/taxonomies.json"
PYTHON_TARGET = ROOT / "services/api/app/generated/taxonomies.py"
TYPESCRIPT_TARGET = ROOT / "apps/web/src/generated/taxonomies.ts"


def render_python(version: str, taxonomies: dict[str, list[str]]) -> str:
    lines = [
        '"""Generated by scripts/generate_contracts.py. Do not edit."""',
        "",
        "from enum import StrEnum",
        "",
        f'SCHEMA_VERSION = "{version}"',
        "",
        "",
    ]
    for index, (name, values) in enumerate(taxonomies.items()):
        lines.extend([f"class {name}(StrEnum):"])
        lines.extend(f'    {value} = "{value}"' for value in values)
        if index < len(taxonomies) - 1:
            lines.extend(["", ""])
    return "\n".join(lines) + "\n"


def render_typescript(version: str, taxonomies: dict[str, list[str]]) -> str:
    lines = [
        "// Generated by scripts/generate_contracts.py. Do not edit.",
        "",
        f'export const SCHEMA_VERSION = "{version}" as const;',
        "",
    ]
    for name, values in taxonomies.items():
        rendered = ", ".join(json.dumps(value) for value in values)
        lines.extend(
            [
                f"export const {name}Values = [{rendered}] as const;",
                f"export type {name} = (typeof {name}Values)[number];",
                "",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    source = json.loads(SOURCE.read_text())
    outputs = {
        PYTHON_TARGET: render_python(source["schema_version"], source["taxonomies"]),
        TYPESCRIPT_TARGET: render_typescript(source["schema_version"], source["taxonomies"]),
    }
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text() != content
    ]
    if args.check:
        if stale:
            paths = ", ".join(str(path.relative_to(ROOT)) for path in stale)
            print("Generated contracts are stale: " + paths)
            return 1
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
